### PR TITLE
Problems when building package

### PR DESCRIPTION
**Pull request by anton-etype**
I had some issues when building the project. Turns out there was some minor typos that caused the errors. This pull request should fix that.

### CODE REVIEW

**Review by Silviculturalist — APPROVED** [review]
Removed treeHistory data. The framework should not be included in this package.

**Comment by Silviculturalist** [comment]
Does it work now?

**Comment by anton-etype** [comment]
Yes! Now I can install it directly from the main bransch  🙌

**Comment by Silviculturalist** [comment]
Can you try again, I just pushed an update from my local main removing some scrap functions.

**Comment by anton-etype** [comment]
Now there is an error again, due to that the NAMESPACE is not updated. 

`Error: package or namespace load failed for 'forester' in namespaceExport(ns, exports):
 undefined exports: siteData, thinning_response_Hynynen_2019`
 
You can probably fix it by running `devtools::document()`

**Pull request merged**
